name: Feature Request
description: Have a new idea/feature for NoExGen?
labels: ["new feature idea"]
body:
  - type: textarea #description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea #solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
      placeholder: Kindly elaborate.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else I should know about this Feature?
    validations:
      required: false